source 'https://github.com/CocoaPods/Specs.git'

target 'CESDividerView', :exclusive => true do
  pod "CESDividerView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CESDividerView", :path => "../"

  
end
